# -*- coding: utf-8 -*-
"""Multivariate Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WYtu3zY0tAPr2rtEBhJYOiLUyNR6t3sh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets
import statsmodels.api as sm

final_data = pd.read_csv('/content/drive/MyDrive/Final Data - Sheet1.csv')

final_data
final_data.fillna(0)
final_data

"""**Year 2016**


"""

target_1 = pd.DataFrame(final_data, columns=["GD1","IN1","GRAD1","HHLIT1","HHGRAD1","HHGRADMU1","HHGRADMI1","AGRI1","BUS1","ENTR1","HOMEWRK1","IND1","FEM1","FEMDOM1",	"MALE1"	,"MALEDOM1",	"HHSEN1",	"HHCH1",	"HHGR1",	"YO1"	,"SE1"])
target_1= target_1.replace(np.nan, 0) 
X1= target_1
y1= final_data["UR1"]

model = sm.OLS(y1, X1).fit()
predictions = model.predict(X1)
 # make the predictions by the model

# Print out the statistics
model.summary()

"""**Year 2017**

"""

target_2 = pd.DataFrame(final_data, columns=["GD2","IN2","GRAD2","HHLIT2","HHGRAD2","HHGRADMU2","HHGRADMI2","AGRI2","BUS2","ENTR2","HOMEWRK2","IND2","FEM2","FEMDOM2",	"MALE2"	,"MALEDOM2",	"HHSEN2",	"HHCH2",	"HHGR2",	"YO2"	,"SE2"])
target_2.fillna(0)
target_2
X2= target_2
y2= final_data["UR2"]

model = sm.OLS(y2, X2).fit()
predictions = model.predict(X1)
 # make the predictions by the model

# Print out the statistics
model.summary()

"""**Year 2018**"""

target_3 = pd.DataFrame(final_data, columns=["GD3","IN3","GRAD3","HHLIT3","HHGRAD3","HHGRADMU3","HHGRADMI3","AGRI3","BUS3","ENTR3","HOMEWRK3","IND3","FEM3","FEMDOM3",	"MALE3"	,"MALEDOM3",	"HHSEN3",	"HHCH3",	"HHGR3",	"YO3"	,"SE3"])
target_3.fillna(0)
target_3
X3= target_3
y3= final_data["UR3"]

model = sm.OLS(y3, X3).fit()
predictions = model.predict(X3)
 # make the predictions by the model

# Print out the statistics
model.summary()

"""**Year 2019**"""

target_4 = pd.DataFrame(final_data, columns=["GD4","IN4","GRAD4","HHLIT4","HHGRAD4","HGRADMU4","HHGRADMI4","AGRI4","BUS4","ENTR4","HOMEWRK4","IND4","FEM4","FEMDOM4",	"MALE4"	,"MALEDOM4",	"HHSEN4",	"HHCH4",	"HHGR4",	"YO4"	,"SE4"])
target_4.fillna(0)
target_4
X4= target_4
y4= final_data["UR4"]

model = sm.OLS(y4, X4).fit()
predictions = model.predict(X4)
 # make the predictions by the model

# Print out the statistics
model.summary()

"""**Year 2020**"""

target_5 = pd.DataFrame(final_data, columns=["GD5","IN5","GRAD5","HHLIT5","HHGRAD5","HGRADMU5","HHGRADMI5","AGRI5","BUS5","ENTR5","HOMEWRK5","IND5","FEM5","FEMDOM5",	"MALE5"	,"MALEDOM5",	"HHSEN5",	"HHCH5",	"HHGR5",	"YO5"	,"SE5"])
target_5.fillna(0)
target_5
X5= target_5
y5= final_data["UR4"]

model = sm.OLS(y4, X4).fit()
predictions = model.predict(X4)
 # make the predictions by the model

# Print out the statistics
model.summary()